name: 'Code Quality Checks(v2)'
on:
  pull_request:
    types: ["opened", "reopened", "synchronize"]

jobs:
  cancel_previous:
    name: 'Cancel previous Code Quality Checks(v2)'
    runs-on: ubuntu-latest
    steps:
      - uses: styfle/cancel-workflow-action@0.11.0
        with:
          workflow_id: ${{ github.event.workflow.id }}

  build:
    name: Code Quality Checks(v2)
    needs: cancel_previous
    runs-on: macos-latest

    steps:
      - name: Checkout source branch
        uses: actions/checkout@v4

      - name: Install xcpretty
        run: gem install xcpretty

      - name: Install Cocoapods
        run: gem install cocoapods

      - name: Execute pod lint
        run: pod lib lint Rudder.podspec --no-clean --allow-warnings --include-podspecs=RudderInternal.podspec
